---
# I can get rid of this if not committed yet. We are gonna do this
# from the controller ci-node.
# ** delete me

# destroy instance

- name: get instance info 
  linode.cloud.api_request:
    api_token: '{{ token_password }}'
    #api_token: "{{ lookup('env', 'TOKEN_PASSWORD') }}"
    path: "linode/instances/{{ lookup('env', 'LINODE_ID') }}"
    method: GET
  register: instance_info

- name: set instance label
  set_fact:
    instance_label: "{{ instance_info.body['label']  }}"

- name: removing instance 
  linode.cloud.instance:
    label: '{{ instance_label }}'
    api_token: '{{ token_password }}'
    #api_token: "{{ lookup('env', 'TOKEN_PASSWORD') }}"
    state: absent