# linode ansible playbook

- name: configuring lamp
  hosts: localhost
  connection: local
  gather_facts: true
  any_errors_fatal: true
  user: root
  vars_files:
    - group_vars/linode/vars

  tasks:
    - block:
        - name: run roles
          include_role:
            name: "{{ item }}"
          loop:
            - common
            - lamp
            - post
        - name: deployment passed
          import_tasks: ../linode_helpers/roles/cilog/tasks/main.yml
          vars:
            deploy_status: 'successful'
      rescue:
        - name: deployment failed
          import_tasks: ../linode_helpers/roles/cilog/tasks/main.yml
          vars:
            deploy_status: 'failed'
      always:
        - name: removing the instance
          include_tasks: destroy
      when: "mode == 'staging'"

    - name: running app normally
      include_role:
        name: "{{ item }}"
      loop:
        - common
        - lamp
        - post
